import _ from 'lodash';

const AvatarTypeList = [
  'gender',
  'clothType',
  'glass',
  'eyeBrow',
  'cheeks',
  'eyelashes',
  'eyeSkin',
  'eyePupil',
  'eyeWhite',
  'face',
  'beard',
  'nose',
  'smile',
  'accessory',
  'logo',
  'shoes',
  'hair',
  'cloth',
];

const AvatarObjectList = {
  genderObjects: [
    {
      name: 'male',
    },
    {
      name: 'female',
    },
  ],
  clothTypeObjects: [
    {
      name: 'full',
    },
    {
      name: 'upper',
    },
  ],
  glassObjects: [
    { selected: 'GLS1', name: 'Glasses' },
    { selected: 'GLS1', name: 'GlassesFBXASC032Frame' },
  ],
  eyeBrowObjects: [
    { selected: 'EBS1', name: 'upward' },
    { selected: 'EBS2', name: 'straight' },
    { selected: 'EBS3', name: 'steep_arch' },
    { selected: 'EBS4', name: 'S_shaped' },
    { selected: 'EBS5', name: 'ROUNDED' },
    { selected: 'EBS6', name: 'Arched1' },
  ],
  cheeksObjects: [
    { selected: 'CK1', name: 'Cheeks_1' },
    { selected: 'CK2', name: 'Cheeks_2' },
    { selected: 'CK3', name: 'Cheeks_3' },
    { selected: 'CK4', name: 'Cheeks_4' },
    { selected: 'CK5', name: 'Cheeks_5' },
    { selected: 'CK6', name: 'Cheeks_6' },
    { selected: 'CK7', name: 'Cheeks_7' },
    { selected: 'CK8', name: 'Cheeks_8' },
    { selected: 'CK9', name: 'Cheeks_9' },
    { selected: 'CK10', name: 'Cheeks_10' },
  ],
  eyelashesObjects: [
    { selected: 'ES1', name: 'Eyelash_1' },
    { selected: 'ES2', name: 'Eyelash_2' },
    { selected: 'ES3', name: 'Eyelash_3' },
    { selected: 'ES4', name: 'Eyelash_4' },
    { selected: 'ES5', name: 'Eyelash_5' },
    { selected: 'ES6', name: 'Eyelash_6' },
    { selected: 'ES7', name: 'Eyelash_7' },
    { selected: 'ES8', name: 'Eyelash_8' },
  ],
  eyeSkinObjects: [
    { selected: 'ES1', name: '_Eye_1FBXASC032Skin' },
    { selected: 'ES6', name: '_Eye_6FBXASC032Skin' },
    { selected: 'ES8', name: '_Eye_8FBXASC032Skin' },
  ],
  eyePupilObjects: [
    { selected: 'ES1', name: '_Eye_1FBXASC032Pupil' },
    { selected: 'ES2', name: '_Eye_2FBXASC032Pupil' },
    { selected: 'ES3', name: '_Eye_3FBXASC032Pupil' },
    { selected: 'ES4', name: '_Eye_4FBXASC032Pupil' },
    { selected: 'ES5', name: '_Eye_5FBXASC032Pupil' },
    { selected: 'ES6', name: '_Eye_6FBXASC032Pupil' },
    { selected: 'ES7', name: '_Eye_7FBXASC032Pupil' },
    { selected: 'ES8', name: '_Eye_8FBXASC032Pupil' },
  ],
  eyeWhiteObjects: [
    { selected: 'ES1', name: '_Eye_1FBXASC032White' },
    { selected: 'ES2', name: '_Eye_2FBXASC032White' },
    { selected: 'ES3', name: '_Eye_3FBXASC032White' },
    { selected: 'ES4', name: '_Eye_4FBXASC032White' },
    { selected: 'ES6', name: '_Eye_6FBXASC032White' },
    { selected: 'ES7', name: '_Eye_7FBXASC032White' },
    { selected: 'ES8', name: '_Eye_8FBXASC032White' },
  ],
  faceObjects: [
    { selected: 'F1', name: 'Head_Geo' },
    { selected: 'F2', name: 'Dog_Geo' },
    { selected: 'F2', name: 'Dog_GeoFBXASC032Eyes' },
    { selected: 'F3', name: 'elephant' },
    { selected: 'F3', name: 'elephantFBXASC032Eyes' },
    { selected: 'F4', name: 'Cow_Geo' },
    { selected: 'F4', name: 'Cow_Eyes' },
    { selected: 'F5', name: 'Panda' },
    { selected: 'F6', name: 'Pig' },
    { selected: 'F6', name: 'PigFBXASC032Eyes' },
  ],
  beardObjects: [
    { selected: 'BE1', name: 'Beard_1' },
    { selected: 'BE2', name: 'Beard_2' },
    { selected: 'BE3', name: 'Beard_3' },
    { selected: 'BE4', name: 'Beard_4' },
    { selected: 'BE5', name: 'Beard_5' },
    { selected: 'BE6', name: 'Beard_6' },
    { selected: 'BE7', name: 'Beard_7' },
    { selected: 'BE8', name: 'Beard_8' },
  ],
  noseObjects: [
    { selected: 'NE1', name: 'nose_1' },
    { selected: 'NE2', name: 'nose_2' },
    { selected: 'NE3', name: 'nose_3' },
    { selected: 'NE4', name: 'nose_4' },
    { selected: 'NE5', name: 'nose_5' },
    { selected: 'NE6', name: 'nose_6' },
    { selected: 'NE7', name: 'nose_7' },
    { selected: 'NE8', name: 'nose_8' },
    { selected: 'NE9', name: 'nose_9' },
    { selected: 'NE10', name: 'nose_10' },
    { selected: 'NE11', name: 'nose_11' },
    { selected: 'NE12', name: 'nose_12' },
  ],
  smileObjects: [
    { selected: 'MH1', name: 'smile_1' },
    { selected: 'MH2', name: 'smile_2' },
    { selected: 'MH3', name: 'smile_3' },
    { selected: 'MH4', name: 'smile_4' },
    { selected: 'MH5', name: 'smile_5' },
    { selected: 'MH6', name: 'smile_6' },
    { selected: 'MH7', name: 'smile_7' },
    { selected: 'MH8', name: 'smile_8' },
  ],
  accessoryObjects: [
    { selected: 'AS1', name: 'Apple' },
    { selected: 'AS2', name: 'Fish_ball' },
    { selected: 'AS3', name: 'Banana' },
    { selected: 'AS4', name: 'Book' },
    { selected: 'AS5', name: 'Bottle' },
    { selected: 'AS6', name: 'Fish' },
    { selected: 'AS7', name: 'Orange' },
    { selected: 'AS7', name: 'OrangeFBXASC032Leaf' },
    { selected: 'AS8', name: 'Pan' },
    { selected: 'AS8', name: 'PanFBXASC032Egg' },
    { selected: 'AS9', name: 'Sword' },
    { selected: 'AS10', name: 'bubble_tea' },
    { selected: 'AS10', name: 'bubble_tea1FBXASC032Cup' },
    { selected: 'AS11', name: 'Trophy' },
  ],
  logoObjects: [
    { selected: 'LOGO5', name: 'Logo_1' },
    { selected: 'LOGO4', name: 'Logo_2' },
    { selected: 'LOGO3', name: 'Logo_3' },
    { selected: 'LOGO4', name: 'Logo_4' },
    { selected: 'LOGO1', name: 'Logo_5' },
    { selected: 'LOGO6', name: 'Logo_6' },
  ],
  shoesObjects: [
    { selected: 'SH1', name: 'Shoes2' },
    { selected: 'SH2', name: 'shoe2_Geo' },
    { selected: 'SH3', name: 'shoe3' },
    { selected: 'SH4', name: 'Shoes4' },
    { selected: 'SH5', name: 'Shoes5' },
    { selected: 'SH6', name: 'Shoes6' },
    { selected: 'SH7', name: 'Shoes13' },
    { selected: 'SH8', name: 'Shoes8' },
    { selected: 'SH9', name: 'Shoes7' },
    { selected: 'SH10', name: 'shoe10' },
    { selected: 'SH11', name: 'Shoes11' },
    { selected: 'SH12', name: 'shoe1_Geo' },
    { selected: 'SH13', name: 'Shoes9' },
  ],
  femaleHairObjects: [
    { selected: 'GHS1', name: 'GirlHair1' },
    { selected: 'GHS2', name: 'GirlHair2' },
    { selected: 'GHS3', name: 'GirlHair3' },
    { selected: 'GHS4', name: 'GirlHair4' },
    { selected: 'GHS5', name: 'GirlHair5' },
    { selected: 'GHS6', name: 'GirlHair6' },
    { selected: 'GHS7', name: 'GirlHair7' },
    { selected: 'GHS8', name: 'GirlHair8' },
    { selected: 'GHS9', name: 'GirlHair9' },
    { selected: 'GHS10', name: 'GirlHair10' },
    { selected: 'GHS11', name: 'GirlHair11' },
    { selected: 'GHS12', name: 'GirlHair12' },
  ],
  maleHairObjects: [
    { selected: 'BHS1', name: 'BoysHair1' },
    { selected: 'BHS2', name: 'BoysHair2' },
    { selected: 'BHS3', name: 'BoysHair3' },
    { selected: 'BHS4', name: 'BoysHair4' },
    { selected: 'BHS6', name: 'BoysHair5' },
    { selected: 'BHS7', name: 'BoysHair6' },
    { selected: 'BHS8', name: 'BoysHair7' },
    { selected: 'BHS9', name: 'BoysHair8' },
    { selected: 'BHS10', name: 'BoysHair9' },
    { selected: 'BHS12', name: 'BoysHair10' },
  ],
  femaleFullClothObjects: [
    { selected: 'GFCS1', name: 'GirlUpper6' },
    { selected: 'GFCS2', name: 'GirlUpper9' },
    { selected: 'GFCS3', name: 'GirlCloth10' },
    { selected: 'GFCS4', name: 'GirlUpper11' },
    { selected: 'GFCS5', name: 'GirlUpper12' },
  ],
  femaleUpperClothObjects: [
    { selected: 'GUCS1', name: 'GirlUpper1' },
    { selected: 'GUCS2', name: 'GirlUpper2' },
    { selected: 'GUCS3', name: 'GirlUpper3' },
    { selected: 'GUCS4', name: 'GirlUpper4' },
    { selected: 'GUCS5', name: 'GirlUpper5' },
    { selected: 'GUCS6', name: 'GirlUpper7' },
    { selected: 'GUCS7', name: 'GirlUpper8' },
    { selected: 'GUCS8', name: 'GirlUpper13' },
    { selected: 'GUCS9', name: 'GirlUpper14' },
    { selected: 'GUCS10', name: 'GirlUpper15' },
    { selected: 'GUCS11', name: 'GirlUpper16' },
    { selected: 'GUCS12', name: 'GirlUpper17' },
    { selected: 'GUCS13', name: 'GirlUpper18' },
  ],
  maleUpperClothObjects: [
    { selected: 'BUCS1', name: 'upper_cloth_01' },
    { selected: 'BUCS2', name: 'upper_cloth_02' },
    { selected: 'BUCS3', name: 'upper_cloth_03' },
    { selected: 'BUCS4', name: 'upper_cloth_04' },
    { selected: 'BUCS5', name: 'upper_cloth_05' },
    { selected: 'BUCS6', name: 'upper_cloth_06' },
    { selected: 'BUCS7', name: 'upper_cloth_07' },
    { selected: 'BUCS8', name: 'upper_cloth_08' },
    { selected: 'BUCS9', name: 'upper_cloth_09' },
    { selected: 'BUCS10', name: 'upper_cloth_10' },
    { selected: 'BUCS11', name: 'upper_cloth_11' },
    { selected: 'BUCS12', name: 'upper_cloth_12' },
  ],
};

// 后面看怎么用threejs的clone函数将骨架和profile结合，这个遍历仅仅是不便支需
const AvatarObjectFlattenList = _.flattenDeep(_.values(AvatarObjectList));

export { AvatarTypeList, AvatarObjectList, AvatarObjectFlattenList };
